services:
  sambadc:
    build: .
    restart: always
    #network_mode: host
    cap_add:
      - CAP_SYS_ADMIN
    hostname: ${SAMBADC_HOSTNAME:-dc1.sad.lan}
    environment:
      DOMAIN_ACTION: provision
      INTERFACES: ${SAMBADC_INTERFACES:-lo eth0}
      WORKGROUP: ${SAMBA_WORKGROUP:-SAD}
      REALM: ${SAMBA_REALM:-sad.lan}
      DNS_FORWARDER: 8.8.8.8
      TZ: ${TZ:-UTC}
      LOG_LEVEL: 5
    volumes:
      - ./vols/etc:/etc/samba      
      - ./vols/lib:/var/lib/samba
    ports:
      - 53:53
      - 53:53/udp
      - 88:88
      - 88:88/udp
      - 135:135
      - 137-138:137-138/udp
      - 139:139
      - 389:389
      - 389:389/udp
      - 445:445
      - 464:464
      - 464:464/udp
      - 636:636
      - 3268-3269:3268-3269
    secrets:
      - samba-admin-password

  db:
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: always
    volumes:
      - ./vols/db:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:apache
    restart: always
    volumes:
      - ./vols/nextcloud:/var/www/html:z
    environment:
      - VIRTUAL_HOST=localhost
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - ./vols/nextcloud:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - ./vols/certs:/etc/nginx/certs:z,ro
      - ./vols/vhost.d:/etc/nginx/vhost.d:z
      - ./vols/html:/usr/share/nginx/html:z
      - /var/run/docker.sock:/tmp/docker.sock:z,ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: nginxproxy/acme-companion
    restart: always
    volumes:
      - ./vols/certs:/etc/nginx/certs:z
      - ./vols/acme:/etc/acme.sh:z
      - ./vols/vhost.d:/etc/nginx/vhost.d:z
      - ./vols/html:/usr/share/nginx/html:z
      - /var/run/docker.sock:/var/run/docker.sock:z,ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

networks:
  proxy-tier:

secrets:
  samba-admin-password:
    file: ../adm-passwd.txt
