services:
  web:
    image: nginx
    container_name: nginx
    labels:
      - sh.acme.autoload.domain=wikicau.duckdns.org
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  acme.sh:
    image: neilpang/acme.sh
    container_name: acme.sh    
    command: daemon
    volumes:
      - ./acmeout:/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      - DEPLOY_DOCKER_CONTAINER_LABEL=sh.acme.autoload.domain=wikicau.duckdns.org
      - DEPLOY_DOCKER_CONTAINER_KEY_FILE=/etc/nginx/ssl/wikicau.duckdns.org/key.pem
      - DEPLOY_DOCKER_CONTAINER_CERT_FILE="/etc/nginx/ssl/wikicau.duckdns.org/cert.pem"
      - DEPLOY_DOCKER_CONTAINER_CA_FILE="/etc/nginx/ssl/wikicau.duckdns.org/ca.pem"
      - DEPLOY_DOCKER_CONTAINER_FULLCHAIN_FILE="/etc/nginx/ssl/wikicau.duckdns.org/full.pem"
      - DEPLOY_DOCKER_CONTAINER_RELOAD_CMD="service nginx force-reload"


networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1