services:
  sambadc:
    build: .
    restart: always
    #network_mode: host
    cap_add:
      - CAP_SYS_ADMIN
    hostname: ${SAMBADC_HOSTNAME:-dc1.sad.lan}
    environment:
      DOMAIN_ACTION: provision
      INTERFACES: ${SAMBADC_INTERFACES:-lo eth0}
      REALM: ${SAMBA_REALM:-sad.lan}
      TZ: ${TZ:-UTC}
      WORKGROUP: ${SAMBA_WORKGROUP:-SAD}
      ALLOW_LDAP_INSECURE: false
      DNS_FORWARDER: 8.8.8.8
      LOG_LEVEL: 5
    volumes:
      - ./vols/etc:/etc/samba      
      - ./vols/lib:/var/lib/samba
    ports:
      - 53:53
      - 53:53/udp
      - 88:88
      - 88:88/udp
      - 135:135
      - 137-138:137-138/udp
      - 139:139
      - 389:389
      - 389:389/udp
      - 445:445
      - 464:464
      - 464:464/udp
      - 636:636
      - 3268-3269:3268-3269
    networks:
      - samba-network
    secrets:
      - samba-admin-password

  phpLDAPadmin:
    image: leenooks/phpldapadmin:2.0.0-dev
    environment:
      - APP_KEY='base64:qrBBHjPRWWDzhFzrKOlTnVVe71j6GzWyQwsMOXbEGo4='
      - APP_URL='http://127.0.0.1:8080'
      - APP_TIMEZONE=UTC
      - LDAP_HOST=dc1.sad.lan
      - LDAP_USERNAME=administrator@sad.lan
      - LDAP_PASSWORD=Admin123
      - LDAP_BASE_DN=dc=sad,dc=lan
      - LDAP_CACHE=true
      - CACHE_DRIVER=memcached
      - MEMCACHED_START=TRUE
    ports:
      - 8000:80
    networks:
      - samba-network

  adwebmanager:
    build:
      context: ./AD-webmanager
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=RANDOM_STRING
      - LDAP_DOMAIN=SAD.LAN
      - SEARCH_DN=DC=sad,DC=lan
      - DEBUG=True
      - USE_LOGGING=True
      - ADMIN_GROUP=Domain Admins
      - LDAP_SERVER=dc1.sad.lan
      - SICCIP_AWARE=False
      - TIMEZONE=Europe/Madrid
    ports:
      - 8080:8080
    networks:
      - samba-network

secrets:
  samba-admin-password:
    file: ../adm-passwd.txt

networks:
  samba-network: